export const FAILURE_CODES = Object.freeze([
  "HARNESS_RPC_TIMEOUT",
  "HARNESS_CHILD_TERMINAL_TIMEOUT",
  "HARNESS_CHILD_SETTLEMENT_TIMEOUT",
  "HARNESS_CHILD_SPAWN_FAILED",
  "HARNESS_COORDINATOR_DECISION_INVALID",
  "HARNESS_COORDINATOR_TURN_LIMIT",
  "HARNESS_SCHEDULER_REJECTED",
  "HARNESS_CHILD_FAILED",
  "HARNESS_CANCELLED",
  "HARNESS_LINEAGE_MISMATCH",
  "HARNESS_EVIDENCE_FAILED",
  "HARNESS_VERIFIER_FAILED",
  "HARNESS_WORKTREE_FAILED",
  "HARNESS_GATE_TIMEOUT",
  "HARNESS_SESSION_INTERRUPTED",
  "HARNESS_SCHEDULER_PERSISTENCE_FAILED",
  "HARNESS_SEMANTIC_REVIEW_FAILED",
  "HARNESS_SECURITY_REVIEW_UNAVAILABLE",
  "HARNESS_SECURITY_REVIEW_FAILED",
  "HARNESS_UNKNOWN",
]);

const knownCodes = new Set(FAILURE_CODES);

export function isFailureCode(value) {
  return typeof value === "string" && knownCodes.has(value);
}

export function safeFailureCode(value) {
  return isFailureCode(value) ? value : "HARNESS_UNKNOWN";
}
